eTicketBooking/Controllers/ActorsController.cs
using eTicketBooking.Data;
using eTicketBooking.Data.Services;
using eTicketBooking.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;


namespace eTicketBooking.Controllers
{
    public class ActorsController : Controller
    {
        private readonly IActorsService _service;
        private readonly AppDbContext _context;
        public ActorsController(IActorsService service, AppDbContext context)
        {
            _service = service;
            _context = context;
        }
       
        //GET ALL
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }

        public async Task<IActionResult> Users()
        {
            var users = await _context.Users.ToListAsync();
            return View(users);
        }

        //Get: Action/Create
        public IActionResult Create() 
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName,ProfilePicture,Bio")]Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            string uniqueFileName = _service.UploadedFile(actor);
            actor.ProfilePictureURL = uniqueFileName;
            await _service.AddAsync(actor);
            return RedirectToAction(nameof(Index));
        }

        //Get Actors/Details/id
        public async Task<IActionResult> Details(int id)
        {
            var actorsDetails = await _service.GetByIdAsync(id);
            if (actorsDetails == null)
            {
                return View("Empty");
            }
            return View(actorsDetails);
        }

        //Get: Action/Update/1
        public async Task<IActionResult> Edit(int id)
        {
            var actorsDetails = await _service.GetByIdAsync(id);

            if (actorsDetails == null)
            {
                return View("Not Found");
            }

            return View(actorsDetails);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,ProfilePicture,Bio")] Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            string uniqueFileName = _service.UploadedFile(actor);
            actor.ProfilePictureURL = uniqueFileName;
            await _service.UpdateAsync(id, actor);
            return RedirectToAction(nameof(Index));
        }

        //Get: Action/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var actorsDetails = await _service.GetByIdAsync(id);

            if (actorsDetails == null)
            {
                return View("Not Found");
            }

            return View(actorsDetails);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var actorsDetails = await _service.GetByIdAsync(id);
            if (actorsDetails == null) return View("Not Found");
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));

        }
    }
}

eTicketBooking/Controllers/CinemasController.cs
using eTicketBooking.Data;
using eTicketBooking.Data.Services;
using eTicketBooking.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eTicketBooking.Controllers
{
    public class CinemasController : Controller
    {
        private readonly ICinemaService _service;
        public CinemasController(ICinemaService service)
        {
            _service = service;
        }
        public async Task<ActionResult> Index()
        {
            var allCinemas = await _service.GetAllAsync();
            return View(allCinemas);
        }
        //Get: Action/Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Logo,Name,Description")]Cinema cinema)
        {
            if (!ModelState.IsValid)
            {
                return View(cinema);
            }
            string uniqueFileName = _service.UploadedFile(cinema);
            cinema.LogoURL = uniqueFileName;
            await _service.AddAsync(cinema);
            return RedirectToAction(nameof(Index));

        }
        //Get Details/id
        public async Task<IActionResult> Details(int id)
        {
            var cinemaDetails = await _service.GetByIdAsync(id);
            if(cinemaDetails == null)
            {
                return View("Not Found");
            }
            return View(cinemaDetails);
        }
        //Get Edit/id
        public async Task<IActionResult> Edit(int id)
        {
            var cinemaDetails = await _service.GetByIdAsync(id);
            if(cinemaDetails == null)
            {
                return View("Not Found");
            }
            return View(cinemaDetails);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id,[Bind("Id,Logo,Name,Description")] Cinema cinema)
        {
            if (!ModelState.IsValid)
            {
                return View(cinema);
            }
            string uniqueFileName = _service.UploadedFile(cinema);
            cinema.LogoURL = uniqueFileName;
            await _service.UpdateAsync(id, cinema);
            return RedirectToAction(nameof(Index));
        }
        //Get Delete/id
        public async Task<IActionResult> Delete(int id)
        {
            var cinemaDetails = await _service.GetByIdAsync(id);
            if(cinemaDetails == null)
            {
                return View("Not Found");
            }
            return View(cinemaDetails);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

eTicketBooking/Controllers/MoviesController.cs
using eTicketBooking.Data;
using eTicketBooking.Data.Services;
using eTicketBooking.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eTicketBooking.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMoviesService _service;
        public MoviesController(IMoviesService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var allMovies = await _service.GetAllAsync(n => n.Cinema);
            return View(allMovies);
        }
        //Get Movies/Filter
        public async Task<IActionResult> Filter(string searchString)
        {
            searchString = searchString.ToLower();
            var allMovies = await _service.GetAllAsync(n => n.Cinema);
            
            if (!string.IsNullOrEmpty(searchString.ToLower()))
            {
                var stringCheck = allMovies.Select(n => n.Name.ToLower());
                if (stringCheck.Contains(searchString)){
                    var filteredResult = allMovies.Where(n => n.Name.ToLower().Contains(searchString) || n.Description.Contains(searchString));

                    return View("Index", filteredResult);
                }
                TempData["Error"] = "Result not found";
                return View("Empty",searchString.ToLower());

            }
          
            return View("Index",allMovies);
        }

        //Get Movies/Details/id
        public async Task<IActionResult> Details(int id)
        {
            var movieDetails = await _service.GetMovieByIdAsync(id);
            if(movieDetails == null)
            {
                return View("Not Found");
            }
            return View(movieDetails);
        }
        //Get Movies/Create/id
        public async Task<IActionResult> Create()
        {
            var movieDropDownsData = await _service.GetNewMovieDropdownsValues();

            ViewBag.Cinemas = new SelectList(movieDropDownsData.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropDownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropDownsData.Actors, "Id", "FullName");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(NewMovieVM movie)
        {
            if (!ModelState.IsValid)
            {
                var movieDropDownsData = await _service.GetNewMovieDropdownsValues();

                ViewBag.Cinemas = new SelectList(movieDropDownsData.Cinemas, "Id", "Name");
                ViewBag.Producers = new SelectList(movieDropDownsData.Producers, "Id", "FullName");
                ViewBag.Actors = new SelectList(movieDropDownsData.Actors, "Id", "FullName");
                return View(movie);
            }
            var uniqueFileName = _service.UploadedFile(movie);
            movie.ImageURL = uniqueFileName;

            await _service.AddNewMovieAsync(movie);
            return RedirectToAction(nameof(Index));

        }
        public async Task<IActionResult> Edit(int id)
        {
            var movieDetails = await _service.GetMovieByIdAsync(id);
            if(movieDetails == null)
            {
                return View("Not Found");
            }

            var response = new NewMovieVM()
            {
                Id = movieDetails.Id,
                Name = movieDetails.Name,
                Price = movieDetails.Price,
                StartDate = movieDetails.StartDate,
                EndDate = movieDetails.EndDate,
                Description = movieDetails.Description,
                ImageURL = movieDetails.ImageURL,
                MovieCategory = movieDetails.MovieCategory,
                CinemaId = movieDetails.CinemaId,
                ProducerId = movieDetails.ProducerId,
                ActorId = movieDetails.Actors_Movies.Select(n => n.ActorId).ToList(),
            };
            

            var movieDropDownsData = await _service.GetNewMovieDropdownsValues();
            ViewBag.Cinemas = new SelectList(movieDropDownsData.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropDownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropDownsData.Actors, "Id", "FullName");
            return View(response);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewMovieVM movie)
        {
            if (id != movie.Id) return View("Not Found");

            if (!ModelState.IsValid)
            {
                var movieDropDownsData = await _service.GetNewMovieDropdownsValues();

                ViewBag.Cinemas = new SelectList(movieDropDownsData.Cinemas, "Id", "Name");
                ViewBag.Producers = new SelectList(movieDropDownsData.Producers, "Id", "FullName");
                ViewBag.Actors = new SelectList(movieDropDownsData.Actors, "Id", "FullName");
                return View(movie);
            }
            var uniqueFileName = _service.UploadedFile(movie);
            movie.ImageURL = uniqueFileName;
            await _service.UpdateMovieAsync(movie);
            return RedirectToAction(nameof(Index));

        }
    }
}

eTicketBooking/Controllers/OrdersController.cs
using eTicketBooking.Data.Cart;
using eTicketBooking.Data.Services;
using eTicketBooking.Data.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace eTicketBooking.Controllers
{

    public class OrdersController : Controller
    {
        private readonly IMoviesService _moviesService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _service;
        public OrdersController(IMoviesService moviesService, ShoppingCart shoppingCart, IOrdersService service)
        {
            _moviesService = moviesService;
            _shoppingCart = shoppingCart;
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var orders = await _service.GetOrdersByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
            
        }
        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;
            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(response);
        }
        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            if (User.Identity.IsAuthenticated)
            {
                var item = await _moviesService.GetMovieByIdAsync(id);
                if (item != null)
                {
                    _shoppingCart.AddItemToCart(item);
                }
                return RedirectToAction(nameof(ShoppingCart));
            }
            TempData["Error"] = "Please signin first";
            return RedirectToAction("Login", "Account");
        }
        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _moviesService.GetMovieByIdAsync(id);
            if (item != null)
            {
                _shoppingCart.RemoveitemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }
         public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _service.StoreOrderAsync(items,userId,userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();
            return View("OrderCompleted");
        }

    }
}

eTicketBooking/Controllers/ProducersController.cs
using eTicketBooking.Data;
using eTicketBooking.Data.Services;
using eTicketBooking.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eTicketBooking.Controllers
{
    public class ProducersController : Controller
    {
        private readonly IProducersService _service;
        public ProducersController(IProducersService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var allProducer = await _service.GetAllAsync();
            return View(allProducer);
        }
        //Show details Producers/1
        public async Task<IActionResult> Details(int id)
        {
            var result = await _service.GetByIdAsync(id);
            return View(result);
        }
        //Create Producers/1
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]//Post method to create Producer
        public async Task<IActionResult> Create([Bind("FullName,ProfilePicture,Bio")] Producer producer)
        {
            if (!ModelState.IsValid)
            {
                return View(producer);
            }
            var uniqueFileName = _service.UploadedFile(producer);
            producer.ProfilePictureURL = uniqueFileName;
            await _service.AddAsync(producer);
            return RedirectToAction(nameof(Index));
        }
        //Edit Producers/1
        public async Task<IActionResult> Edit(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if(result == null)
            {
                return View("Not Found");
            }
            return View(result);
        }
        [HttpPost]//Post method to Edit Producer
        public async Task<IActionResult> Edit(int id, Producer producer)
        {
            if (!ModelState.IsValid)
            {
                return View(producer);
            }
            var uniqueFileName = _service.UploadedFile(producer);
            producer.ProfilePictureURL = uniqueFileName;
            await _service.UpdateAsync(id,producer);
            return RedirectToAction(nameof(Index));
        }
        //Edit Producers/1
        public async Task<IActionResult> Delete(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if (result == null)
            {
                return View("Not Found");
            }
            return View(result);
        }
        [HttpPost]//Post method to Edit Producer
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if(result == null)
            {
                return View("Not Found");
            }
           
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

eTicketBooking/Views/Movies/Create.cshtml
@model NewMovieVM
@using eTicketBooking.Data;
@{
    ViewData["Title"] = "Create a new Movies";
}
<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Create a new movie</h4>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form enctype="multipart/form-data" asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="col-md-6 ">
                            <div class="form-group">
                                <label asp-for="Name" class="control-lable"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="StartDate" class="control-lable"></label>
                                <input asp-for="StartDate" type="date" class="form-control" />
                                <span asp-validation-for="StartDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="EndDate" class="control-lable"></label>
                                <input asp-for="EndDate" type="date" class="form-control" />
                                <span asp-validation-for="EndDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Price" class="control-lable"></label>
                                <input asp-for="Price" type="number" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="PosterImage" class="control-lable"></label>
                                <div class="custom-file">
                                    <input asp-for="PosterImage" class="custom-file-input" id="ProfilePicture"
                                           onchange="document.getElementById('PosterImagePreview').src = window.URL.createObjectURL(this.files[0])" />
                                    <lable class="custom-file-label" for="Logo">Choose File</lable>
                                    <span asp-validation-for="PosterImage" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 ">
                            <div class="form-group">
                                <label asp-for="CinemaId" class="control-lable"></label>
                                <select asp-for="CinemaId" class="form-control" asp-items="ViewBag.Cinemas"></select>
                                <span asp-validation-for="CinemaId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="MovieCategory" class="control-lable"></label>
                                <select asp-for="MovieCategory" class="form-control" asp-items="Html.GetEnumSelectList<MovieCategory>()"></select>
                                <span asp-validation-for="MovieCategory" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ProducerId" class="control-lable"></label>
                                <select asp-for="ProducerId" class="form-control" asp-items="ViewBag.Producers"></select>
                                <span asp-validation-for="ProducerId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ActorId" class="control-lable"></label>
                                <select asp-for="ActorId" class="form-control" asp-items="ViewBag.Actors" multiple></select>
                                <span asp-validation-for="ActorId" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-lable"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 offset-4 text-center">
                        <img class="border-info rounded-circle" style="width:100%;" id="PosterImagePreview" />
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script>
        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>
}

eTicketBooking/Views/Movies/Details.cshtml
@model Movie

@{
    ViewData["Title"] = "Movie details";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <div class="card mb-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-info">
                        <p class="card-text">
                            <h5 class="card-title">
                                @Model.Name
                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="~/images/movies/@Model.ImageURL" width="100%" alt="@Model.Name">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">@Model.Description</p>
                        <p class="card-text">
                            <b>Cinema: </b>
                            <a asp-controller="Cinemas" asp-action="Details" asp-route-id="@Model.CinemaId">
                                @Model.Cinema.Name
                            </a>
                        </p>
                        <p class="card-text">
                            <b>Producer: </b>
                            <a asp-controller="Producers" asp-action="Details" asp-route-id="@Model.ProducerId">
                                @Model.Producer.FullName
                            </a>
                        </p>
                        <p class="card-text"><b>Category: </b>@Model.MovieCategory</p>
                        <p class="card-text"><b>Start Date: </b>@Model.StartDate.ToString("dd MMM yy")</p>
                        <p class="card-text"><b>End Date: </b>@Model.EndDate.ToString("dd MMM yy")</p>
                        <p class="card-text ">
                            <b>Status: </b>
                            @if (DateTime.Now >= Model.StartDate && DateTime.Now <= Model.EndDate)
                            {
                                <span class="badge bg-success text-white">AVAILABLE</span>
                            }
                            else if (DateTime.Now > Model.EndDate)
                            {
                                <span class="badge bg-danger text-white">EXPIRED</span>
                            }
                            else
                            {
                                <span class="badge bg-primary text-white">UPCOMING</span>
                            }
                        </p>
                        <p class="card-text">
                            <b>Actors: </b>
                            <hr />
                            <div class="row">
                                @foreach (var actor in Model.Actors_Movies)
                                {
                                    <div class="column text-center">
                                        <img class="border-info rounded-circle" src="~/images/actors/@actor.Actor.ProfilePictureURL" style="max-width: 150px" />
                                        <br />
                                        <a asp-controller="Actors" asp-action="Details" asp-route-id="@actor.ActorId">@actor.Actor.FullName</a>
                                    </div>
                                }
                            </div>
                        </p>

                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer">
                        <p class="card-text">
                            <a class="btn btn-outline-primary float-right" asp-action="Index">
                                Back to List
                            </a>
                            <a class="btn btn-success text-white" asp-controller="Orders" asp-action="AddItemToShoppingCart" asp-route-id="@Model.Id"><i class="bi bi-cart-plus"></i> Add to Cart (Price @Model.Price.ToString("c"))</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

eTicketBooking/Views/Movies/Empty.cshtml
@if (TempData["Error"] != null)
{
    <div class="row text-center ">
        <div class="col-md-6 offset-3 ">
            <h1 class="text-black-50 alert-danger"><span><b>Sorry!</b> - @TempData["Error"]</span></h1>
            <hr />
            <a class="btn btn-outline-success" asp-controller="Movies" asp-action="Index">Back</a>
        </div>
    </div>
}

eTicketBooking/Views/Movies/Index.cshtml
@model IEnumerable<Movie>

@{
    ViewData["Title"] = "List of Movies";
}

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.Name
                                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                    {
                                        <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                                    }
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="~/images/movies/@item.ImageURL" width="100%" alt="@item.Name">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text">@item.Description</p>
                            <p class="card-text"><b>Cinema: </b>@item.Cinema.Name</p>
                            <p class="card-text"><b>Category: </b>@item.MovieCategory</p>
                            <p class="card-text"><b>Start Date: </b>@item.StartDate.ToString("dd MMM yy")</p>
                            <p class="card-text"><b>End Date: </b>@item.EndDate.ToString("dd MMM yy")</p>
                            <p class="card-text ">
                                <b>Status: </b>
                                @if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
                                {
                                    <span class="badge bg-success text-white">AVAILABLE</span>
                                }
                                else if (DateTime.Now > item.EndDate)
                                {
                                    <span class="badge bg-danger text-white">EXPIRED</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">UPCOMING</span>
                                }
                            </p>

                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right" asp-action="Details" asp-route-id="@item.Id">
                                    <i class="bi bi-eye-fill"></i> Show Details
                                </a>
                                @*@if (!User.IsInRole("Admin"))
                                    {*@
                                <a class="btn btn-success text-white" asp-controller="Orders" asp-action="AddItemToShoppingCart" asp-route-id="@item.Id"><i class="bi bi-cart-plus"></i> Add to Cart (@item.Price Rs)</a>
                                @*
                                    }*@
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>
@await Html.PartialAsync("_CreateItem", "Movies")